#!/bin/bash
printf '%o\n' $(( $((5#$(echo $STIR | tr 'stir.' '01234

'))) + $((5#$(echo $WATER | tr 'water' '01234'))) )) | 

tr '01234567' 'bestchol'
[5/31, 10:15 PM] +234 904 099 9579: printf '%o\n' $(( $((5#$(echo $STIR | tr 'stir.' '01234
'))) + $((5#$(echo $WATER | tr 'water' '01234'))) )) | 
tr '01234567' 'bestchol'
